version: "3.8"

services:

  bitwarden:

    build: ./bitwarden
    container_name: vaultwarden
    restart: unless-stopped
    user: 1504:1504
    ports:
      - ${NEBULA_IP}:8080:8080
    env_file:
      - ./bitwarden/bitwarden.env
    volumes:
      - ${DATA_DIR}/bitwarden/data:/data
      - ${BITWARDEN_TLS_CERT_LOCATION}:/ssl/bitwarden-tls.crt:ro
      - ${BITWARDEN_TLS_KEY_LOCATION}:/ssl/bitwarden-tls.key:ro
