services:

  jellyfin:

    build: ./jellyfin
    container_name: media
    restart: unless-stopped
    user: 1501:1501
    ports:
      - 80:8096
      - 8096:8096
    volumes:
      - ${DATA_DIR}/jellyfin/config:/config
      - ${DATA_DIR}/jellyfin/cache:/cache
      - /mnt/trancodes:/config/transcodes
      - ${DATA_DIR}/media:/media
