version: "3.8"

services:

  ts-dns:

    image: tailscale/tailscale:latest
    hostname: dns
    environment:
      - TS_AUTHKEY=
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ${DATA_DIR}/ts/pihole:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  ns:

    build: ./pihole
    container_name: ns
    restart: unless-stopped
    network_mode: service:ts-dns
    depends_on:
      - ts-dns
    env_file:
      - ./pihole/pihole.env
    volumes:
      - '${DATA_DIR}/dns/cfg:/etc/pihole'
      - '${DATA_DIR}/dns/dnsmasq:/etc/dnsmasq.d'
      - '${CERTS_DIR}/pihole-combined-tls.pem:/ssl/pihole-combined-tls.pem:ro'
